import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../contexts/AuthContext'
import { canManageFinance, canDeleteTransactions } from '../lib/permissions'
import { formatCurrency, formatDate, todayISO } from '../lib/format'
import { toast } from '../components/Toast'
import Modal from '../components/Modal'
import { Plus, Trash2, CheckCircle2, AlertTriangle } from 'lucide-react'
import type { Fine, Member } from '../types'

export default function FinesPage() {
  const { profile } = useAuth()
  const [rows, setRows] = useState<Fine[]>([])
  const [members, setMembers] = useState<Member[]>([])
  const [loading, setLoading] = useState(true)
  const [showAdd, setShowAdd] = useState(false)
  const [form, setForm] = useState({ member_id: '', fine_type: 'late_payment', amount: '', reason: '', issue_date: todayISO() })

  useEffect(() => { load() }, [])

  async function load() {
    setLoading(true)
    await autoGenerateDefaultFines()
    const [fns, mems] = await Promise.all([
      supabase.from('fines').select('*, member:members(full_name)').order('issue_date', { ascending: false }),
      supabase.from('members').select('*').eq('status', 'active').order('full_name'),
    ])
    setRows(fns.data ?? [])
    setMembers(mems.data ?? [])
    setLoading(false)
  }

  async function autoGenerateDefaultFines() {
    const today = todayISO()
    const { data: defaulted } = await supabase.from('loans')
      .select('id, member_id, due_date, balance')
      .eq('status', 'defaulted').gt('balance', 0)
    if (!defaulted || defaulted.length === 0) return
    for (const l of defaulted) {
      const { data: existing } = await supabase.from('fines')
        .select('id').eq('member_id', l.member_id).eq('fine_type', 'loan_default').eq('issue_date', today).maybeSingle()
      if (existing) continue
      const fineAmount = Number(l.balance) * 0.05
      await supabase.from('fines').insert({
        member_id: l.member_id, fine_type: 'loan_default', amount: Math.round(fineAmount),
        reason: `Default on loan due ${formatDate(l.due_date)}`, issue_date: today, recorded_by: profile?.id,
      })
    }
  }

  async function save() {
    if (!form.member_id || !form.amount) { toast('Member and amount required', 'error'); return }
    const { error } = await supabase.from('fines').insert({
      member_id: form.member_id, fine_type: form.fine_type, amount: Number(form.amount),
      reason: form.reason || null, issue_date: form.issue_date, recorded_by: profile?.id,
    })
    if (error) { toast(error.message, 'error'); return }
    toast('Fine recorded'); setShowAdd(false); load()
  }

  async function markPaid(f: Fine) {
    const { error } = await supabase.from('fines').update({ paid: true, paid_date: todayISO() }).eq('id', f.id)
    if (error) { toast(error.message, 'error'); return }
    toast('Fine marked paid'); load()
  }

  async function remove(id: string) {
    if (!confirm('Delete this fine?')) return
    const { error } = await supabase.from('fines').delete().eq('id', id)
    if (error) { toast(error.message, 'error'); return }
    toast('Fine deleted'); load()
  }

  if (loading) return <div className="loading-center"><div className="spinner" /></div>
  const canFinance = canManageFinance(profile?.role)
  const canDelete = canDeleteTransactions(profile?.role)
  const unpaid = rows.filter((r) => !r.paid).reduce((s, r) => s + Number(r.amount), 0)
  const paid = rows.filter((r) => r.paid).reduce((s, r) => s + Number(r.amount), 0)

  return (
    <div>
      <div className="stat-grid">
        <div className="stat-card"><div className="stat-label">Unpaid Fines</div><div className="stat-value">{formatCurrency(unpaid)}</div></div>
        <div className="stat-card"><div className="stat-label">Collected Fines</div><div className="stat-value">{formatCurrency(paid)}</div></div>
        <div className="stat-card"><div className="stat-label">Total Fines</div><div className="stat-value">{rows.length}</div></div>
      </div>
      <div className="card">
        <div className="card-header">
          <h3>Fines</h3>
          {canFinance && <button className="btn btn-primary" onClick={() => setShowAdd(true)}><Plus size={16} /> Issue Fine</button>}
        </div>
        <div className="table-wrap">
          <table className="data-table">
            <thead><tr><th>Member</th><th>Type</th><th>Amount</th><th>Reason</th><th>Issued</th><th>Status</th><th></th></tr></thead>
            <tbody>
              {rows.length === 0 && <tr><td colSpan={7} style={{ textAlign: 'center', color: 'var(--text-muted)' }}>No fines recorded</td></tr>}
              {rows.map((r) => (
                <tr key={r.id}>
                  <td>{r.member?.full_name ?? '—'}</td>
                  <td><span className="badge badge-neutral">{r.fine_type.replace(/_/g, ' ')}</span></td>
                  <td>{formatCurrency(r.amount)}</td>
                  <td>{r.reason ?? '—'}</td>
                  <td>{formatDate(r.issue_date)}</td>
                  <td>{r.paid ? <span className="badge badge-success"><CheckCircle2 size={11} /> Paid</span> : <span className="badge badge-warning"><AlertTriangle size={11} /> Unpaid</span>}</td>
                  <td>
                    <div className="flex gap-2">
                      {canFinance && !r.paid && <button className="btn btn-secondary btn-sm" onClick={() => markPaid(r)}>Mark Paid</button>}
                      {canDelete && <button className="btn-ghost" style={{ color: 'var(--error)' }} onClick={() => remove(r.id)}><Trash2 size={15} /></button>}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      <Modal open={showAdd} onClose={() => setShowAdd(false)} title="Issue Fine" footer={<>
        <button className="btn btn-secondary" onClick={() => setShowAdd(false)}>Cancel</button>
        <button className="btn btn-primary" onClick={save}>Save</button>
      </>}>
        <div className="form-group"><label>Member</label>
          <select value={form.member_id} onChange={(e) => setForm({ ...form, member_id: e.target.value })}>
            <option value="">Select member…</option>
            {members.map((m) => <option key={m.id} value={m.id}>{m.full_name}</option>)}
          </select></div>
        <div className="form-row">
          <div className="form-group"><label>Fine Type</label>
            <select value={form.fine_type} onChange={(e) => setForm({ ...form, fine_type: e.target.value })}>
              <option value="late_payment">Late Payment</option><option value="absenteeism">Absenteeism</option>
              <option value="loan_default">Loan Default</option><option value="other">Other</option>
            </select></div>
          <div className="form-group"><label>Amount (KES)</label><input type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></div>
        </div>
        <div className="form-group"><label>Reason</label><input value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></div>
        <div className="form-group"><label>Issue Date</label><input type="date" value={form.issue_date} onChange={(e) => setForm({ ...form, issue_date: e.target.value })} /></div>
      </Modal>
    </div>
  )
}
