/*
# Delete and recreate member auth accounts with correct password hashes

## Problem
8 member accounts were created via direct SQL INSERT into auth.users with bcrypt
cost factor $2a$06$ (generated by pgcrypto's crypt()). Supabase's GoTrue auth
server requires bcrypt cost $2a$10$. When a user tries to sign in, GoTrue fails
to verify the password hash and returns "Database error querying schema".

## Solution
Delete the 8 broken auth.users rows. Their profile rows cascade-delete via the
profiles.id FK (ON DELETE CASCADE). Then recreate them through the admin API
(supabaseAdmin.auth.admin.createUser) which generates correct bcrypt $2a$10$
password hashes.

## What this migration does
1. Deletes 8 auth.users rows that have incorrect password hashes (cost $2a$06$).
   Only deletes the accounts with $2a$06$ — the original admin (Talia, $2a$10$)
   is preserved.
2. The ON DELETE CASCADE on profiles.id_fk automatically removes the orphaned
   profile rows.

## Safety
- Only deletes accounts with the wrong password hash format ($2a$06$).
- The working admin account ($2a$10$) is NOT affected.
- Recreating accounts is done separately via the admin API edge function.
*/
DELETE FROM auth.users
WHERE encrypted_password LIKE '$2a$06$%';
